export { default as ConnectStack } from './ConnectStack'
export { default as FavouritesStack } from './FavouritesStack'
export { default as HomeStack } from './HomeStack'
export { default as MoviesStack } from './MoviesStack'
export { default as SettingsStack } from './SettingsStack'
